name: Set up dependencies
description: Set up dependencies for the project
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmock-dev libgtest-dev valgrind llvm
