cmake_host_system_information(RESULT HOSTNAME QUERY HOSTNAME)
set(CTEST_SITE "${HOSTNAME}")

cmake_path(GET CMAKE_PARENT_LIST_FILE STEM FNAME)

set(CTEST_SOURCE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build")

find_program(CTEST_GIT_COMMAND git)
if(CTEST_GIT_COMMAND)
    execute_process(
        COMMAND ${CTEST_GIT_COMMAND} rev-parse HEAD
        OUTPUT_VARIABLE GIT_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    string(SUBSTRING ${GIT_COMMIT} 0 7 COMMIT_ID)
    set(CTEST_BUILD_NAME "${COMMIT_ID}-${CMAKE_HOST_SYSTEM_NAME}-${CMAKE_HOST_SYSTEM_PROCESSOR}-${FNAME}")
else()
    set(CTEST_BUILD_NAME "${CMAKE_HOST_SYSTEM_NAME}-${CMAKE_HOST_SYSTEM_PROCESSOR}-${FNAME}")
endif()

set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
